name: OpenMT-Addon
main: nl.mrlucadev.openmtaddon.Main
version: 1.0 BETA
commands:
   mtaddons:
      description: Main command
      aliases: [openmt, openmtaddons, mtaddon]
   alert:
      description: Broadcast een bericht!
      aliases: [bc, broadcast]
   clearchat:
      description: Leeg de chat!
      aliases: [cc, cchat]
   helpmij:
      description: Heb je hulp nodig? Gebruik dit command!
      aliases: [helpme, helpop, hulp]
